services:
  ziti-controller:
    image: openziti/ziti-controller:latest
    container_name: ziti-controller
    ports:
      - "1280:1280"
      - "8440:8440"
    environment:
      ZITI_CTRL_ADVERTISED_ADDRESS: "localhost"
      ZITI_CTRL_ADVERTISED_PORT: "1280"
      ZITI_PWD: "admin"
      ZITI_USER: "admin"
